name: LLama.cpp build

on:
    workflow_dispatch:

jobs:
  llamacpp-build:
    strategy:
        fail-fast: false
        matrix:
          include:
            - platform: "macos-latest"
              args: "-Doptimize=ReleaseFast -Dtarget=x86_64-macos-none -Dcpu=x86_64+avx2+fma+f16c"
              file_extension: ""
              asset_suffix: "-x86_64-apple-darwin"
            - platform: "macos-latest"
              args: "-Doptimize=ReleaseFast -Dtarget=aarch64-macos-none"
              file_extension: ""
              asset_suffix: "-aarch64-apple-darwin"
            - platform: "ubuntu-20.04"
              args: "-Doptimize=ReleaseFast -Dtarget=x86_64-linux-gnu -Dcpu=x86_64+avx2+fma+f16c"
              file_extension: ""
              asset_suffix: "-x86_64-unknown-linux-gnu"
            - platform: "windows-latest"
              args: "-Doptimize=ReleaseFast -Dtarget=x86_64-windows-gnu -Dcpu=x86_64+avx2+fma+f16c"
              file_extension: ".exe"
              asset_suffix: "-x86_64-pc-windows-msvc"
    runs-on: ${{matrix.platform}}
    steps:
      - name: Checkout LLama.cpp Repository
        uses: actions/checkout@v4
        with:
          repository: ggerganov/llama.cpp
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: make file
        run: |
          touch build.zig
          cat "${{ github.action_path }}/build.zig" > build.zig
      - name: Setup Zig & Build LLama.cpp
        uses: goto-bus-stop/setup-zig@v2
        with:
            version: 0.11.0
      - run: zig build ${{matrix.args}}
      - run: ls -l zig-out/bin
      - name: Upload main binary to latest release
        uses: svenstaro/upload-release-action@v2
        with:
            file: zig-out/bin/main${{ matrix.file_extension }}
            release_name: latest
            asset_name: llama.cpp${{ matrix.asset_suffix }}${{ matrix.file_extension }}
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{ github.ref }}
            overwrite: true
      - name: Upload server binary to latest release
        uses: svenstaro/upload-release-action@v2
        with:
            file: zig-out/bin/server${{ matrix.file_extension }}
            release_name: latest
            asset_name: llama.cpp.server${{ matrix.asset_suffix }}${{ matrix.file_extension }}
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{ github.ref }}
            overwrite: true
