name: LLama.cpp build test

on:
  push:
    branches:
      - main

jobs:
  llamacpp-build:
    strategy:
        fail-fast: false
        matrix:
          settings:
            - platform: "macos-latest"
              args: "-Doptimize=ReleaseFast -Dtarget=x86_64-macos-none -Dcpu=x86_64+avx2+fma+f16c"
            - platform: "macos-latest"
              args: "-Doptimize=ReleaseFast -Dtarget=aarch64-macos-none"
            - platform: "ubuntu-20.04"
              args: "-Doptimize=ReleaseFast -Dtarget=x86_64-linux-gnu -Dcpu=x86_64+avx2+fma+f16c"
            - platform: "windows-latest"
              args: "-Doptimize=ReleaseFast -Dtarget=x86_64-windows-gnu -Dcpu=x86_64+avx2+fma+f16c"
    runs-on: ${{matrix.settings.platform}}
    steps:
      - name: Checkout LLama.cpp Repository
        uses: actions/checkout@v4
        with:
          repository: ggerganov/llama.cpp
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
      - run: zig targets
      - run: zig build ${{matrix.settings.args}}

